akka-sample-cluster-java/src/test/resources/reference.conf, akka-sample-cluster-scala/src/test/resources/reference.conf, akka-sample-distributed-data-java/src/test/resources/reference.conf, akka-sample-distributed-data-scala/src/test/resources/reference.conf, akka-sample-multi-node-scala/src/test/resources/reference.conf, akka-sample-remote-java/src/test/resources/reference.conf, akka-sample-remote-scala/src/test/resources/reference.conf
* changes due to new coordinated shutdown behavior
=> Don't shutdown ActorSystem in tests

akka-sample-camel-java/src/main/java/sample/camel/http/HttpTransformer.java, akka-sample-camel-java/src/main/java/sample/camel/route/RouteTransformer.java, akka-sample-cluster-java/src/main/java/sample/cluster/factorial/FactorialBackend.java, akka-sample-cluster-java/src/main/java/sample/cluster/factorial/FactorialFrontend.java, akka-sample-cluster-java/src/main/java/sample/cluster/factorial/MetricsListener.java, akka-sample-cluster-java/src/main/java/sample/cluster/simple/SimpleClusterListener.java, akka-sample-cluster-java/src/main/java/sample/cluster/simple/SimpleClusterListener2.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/StatsAggregator.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/StatsSampleClient.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/StatsService.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/StatsWorker.java, akka-sample-cluster-java/src/main/java/sample/cluster/transformation/TransformationBackend.java, akka-sample-cluster-java/src/main/java/sample/cluster/transformation/TransformationFrontend.java, akka-sample-remote-java/src/main/java/sample/remote/calculator/CalculatorActor.java, akka-sample-remote-java/src/main/java/sample/remote/calculator/CreationActor.java, akka-sample-remote-java/src/main/java/sample/remote/calculator/LookupActor.java
=> update to AbstractActor

akka-sample-cluster-java/src/main/java/sample/cluster/factorial/FactorialBackend.java
Refs #8
There was only one file to convert.
=> use CompletionStage instead of Future in FactorialBackend.java 

akka-sample-javaslang/pom.xml
=> Update Javaslang sample to the latest Akka

akka-sample-persistence-java/pom.xml
=> add missing dependency of leveldb

akka-sample-persistence-java/src/main/java/sample/persistence/PersistentActorExample.java
Fix method reference issue in PersistentActorExample.java. This closes #40
=> Fix method reference issue in PersistentActorExample.java. This closes #40

akka-sample-distributed-data-scala/src/main/scala/sample/distributeddata/ShoppingORCart.scala, akka-sample-distributed-data-scala/src/multi-jvm/scala/sample/distributeddata/ShoppingORCartSpec.scala
* demoes ORMultiMap.emptyWithValueDeltas
* avoids anomalies theoretically possible with LWWMap
=> Additional Shopping Cart example, this time based on ORMultiMap

akka-sample-remote-java/README.md, akka-sample-remote-scala/README.md
Akka samples showcasing akka-remote show stir users towards akka cluster.
=> Adds disclaimer wrt remote vs cluster

akka-sample-cqrs-scala/src/main/scala/sample/cqrs/SwitchEntity.scala
One part of the feedback from https://github.com/akka/akka-samples/issues/86
cc @eloots @kikiya
=> more idiomatic implementation of PersistentActor

akka-sample-persistence-java/src/main/resources/application.conf
=> Remove dated link to activator

akka-sample-cluster-scala/src/main/resources/application.conf
=> Use netty for akka-sample-cluster-scala

akka-sample-camel-java/project/build.properties, akka-sample-camel-scala/project/build.properties, akka-sample-cluster-java/build.sbt, akka-sample-cluster-java/project/build.properties, akka-sample-cluster-scala/build.sbt, akka-sample-cluster-scala/project/build.properties, akka-sample-cqrs-scala/build.sbt, akka-sample-cqrs-scala/project/build.properties, akka-sample-distributed-data-java/build.sbt, akka-sample-distributed-data-java/project/build.properties, akka-sample-distributed-data-scala/build.sbt, akka-sample-distributed-data-scala/project/build.properties, akka-sample-fsm-java/project/build.properties, akka-sample-fsm-scala/project/build.properties, akka-sample-main-java/project/build.properties, akka-sample-main-scala/project/build.properties, akka-sample-multi-node-scala/build.sbt, akka-sample-multi-node-scala/project/build.properties, akka-sample-persistence-dc-java/build.sbt, akka-sample-persistence-dc-java/project/build.properties, akka-sample-persistence-dc-scala/build.sbt, akka-sample-persistence-dc-scala/project/build.properties, akka-sample-persistence-java/project/build.properties, akka-sample-persistence-scala/project/build.properties, akka-sample-sharding-java/build.sbt, akka-sample-sharding-java/project/build.properties, akka-sample-sharding-scala/build.sbt, akka-sample-sharding-scala/project/build.properties, akka-sample-supervision-java/project/build.properties, docs-gen/project/build.properties
=> upgrade dependencies

akka-sample-persistence-java/build.sbt, akka-sample-persistence-java/pom.xml, akka-sample-persistence-java/src/main/java/sample/persistence/SnapshotExample.java, akka-sample-persistence-java/src/main/resources/application.conf, akka-sample-persistence-scala/build.sbt, akka-sample-persistence-scala/src/main/resources/application.conf
Other samples could use it too, just doing this one for now. Removes some scary warnings when running
=> Use jackson for persistent events

akka-sample-sharding-java/build.sbt, akka-sample-sharding-java/src/main/java/sample/sharding/Device.java, akka-sample-sharding-java/src/main/java/sample/sharding/Devices.java, akka-sample-sharding-java/src/main/java/sample/sharding/Message.java, akka-sample-sharding-java/src/main/java/sample/sharding/ShardingApp.java, akka-sample-sharding-java/src/main/resources/application.conf, akka-sample-sharding-scala/build.sbt, akka-sample-sharding-scala/src/main/resources/application.conf, akka-sample-sharding-scala/src/main/scala/sample/sharding/Device.scala, akka-sample-sharding-scala/src/main/scala/sample/sharding/Devices.scala, akka-sample-sharding-scala/src/main/scala/sample/sharding/Message.scala, akka-sample-sharding-scala/src/main/scala/sample/sharding/ShardingApp.scala
* Akka 2.6.0-M3
* Jackson serializer
* correct shard extractor
* misc cleanup
=> Cleanup sharding sample

akka-sample-persistence-scala/src/main/resources/application.conf
=> fix #114 remove broken issue link

.travis.yml
=> same .travis.yml as in 2.5 branch

akka-sample-distributed-data-scala/build.sbt, akka-sample-distributed-data-scala/project/plugins.sbt, akka-sample-distributed-data-scala/src/main/resources/application.conf, akka-sample-distributed-data-scala/src/main/resources/logback.xml, akka-sample-distributed-data-scala/src/main/scala/sample/distributeddata/ReplicatedMetrics.scala, akka-sample-distributed-data-scala/src/multi-jvm/scala/sample/distributeddata/ReplicatedCacheSpec.scala, akka-sample-distributed-data-scala/src/multi-jvm/scala/sample/distributeddata/VotingServiceSpec.scala, akka-sample-distributed-data-scala/src/test/resources/logback-test.xml, akka-sample-distributed-data-scala/src/test/resources/reference.conf
and a few other minor adjustments
=> 2.6.0 in akka-sample-distributed-data-scala

.travis.yml, akka-sample-cqrs-java/LICENSE, akka-sample-cqrs-java/README.md, akka-sample-cqrs-java/build.sbt, akka-sample-cqrs-java/pom.xml, akka-sample-cqrs-java/project/build.properties, akka-sample-cqrs-java/project/plugins.sbt, akka-sample-cqrs-java/src/main/java/sample/cqrs/CassandraSessionExtension.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/CborSerializable.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/EventProcessor.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/EventProcessorSettings.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/EventProcessorStream.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/KeepAlive.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/Main.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCart.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCartEventProcessorStream.java, akka-sample-cqrs-java/src/main/resources/application.conf, akka-sample-cqrs-java/src/main/resources/logback.xml, akka-sample-cqrs-java/src/test/java/sample/cqrs/EventProcessorTest.java, akka-sample-cqrs-java/src/test/java/sample/cqrs/IntegrationTest.java, akka-sample-cqrs-java/src/test/java/sample/cqrs/ShoppingCartTest.java, akka-sample-cqrs-java/src/test/resources/logback-test.xml
Corresponding Scala sample in https://github.com/akka/akka-samples/pull/135
Corresponding Lagom Java sample in https://github.com/lagom/lagom-samples/pull/119
=> akka-sample-cqrs-java with Akka 2.6 and Typed

akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/WeatherServer.scala
=> Simplified graceful shutdown

akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/Aggregator.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/Guardian.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/JsonFormats.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/KillrWeather.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/WeatherRoutes.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/package.scala
Just minor cleanup prior to code walk through for video, simplistic event/processing time added for timeseries.
=> Added simplistic time window for data and minor cleanup.

akka-sample-cqrs-java/src/test/java/sample/cqrs/IntegrationTest.java, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/IntegrationSpec.scala
* sometimes it received duplicate ItemQuantityAdjusted, probably because offset was't written before shutdown
* give it some time to write the offset before shutting down
* subscribe earlier to make sure all events are received
Fixes #160
=> fix IntegrationTest, #160

akka-sample-cluster-client-grpc-java/build.sbt, akka-sample-cluster-client-grpc-java/pom.xml, akka-sample-cluster-client-grpc-java/src/test/java/sample/cluster/client/grpc/ClusterClientTest.java, akka-sample-cluster-client-grpc-scala/build.sbt, akka-sample-cluster-java/build.sbt, akka-sample-cluster-java/pom.xml, akka-sample-cluster-scala/build.sbt, akka-sample-cqrs-java/build.sbt, akka-sample-cqrs-java/pom.xml, akka-sample-cqrs-scala/build.sbt, akka-sample-distributed-data-java/build.sbt, akka-sample-distributed-data-scala/build.sbt, akka-sample-fsm-java/build.sbt, akka-sample-fsm-java/pom.xml, akka-sample-fsm-scala/build.sbt, akka-sample-persistence-dc-java/build.sbt, akka-sample-persistence-dc-java/pom.xml, akka-sample-persistence-dc-scala/build.sbt, akka-sample-persistence-java/build.sbt, akka-sample-persistence-java/pom.xml, akka-sample-persistence-scala/build.sbt, akka-sample-sharding-scala/build.sbt
also use getCountInstance, added in Akka 2.6.1 akka/akka#27728
=> update to Akka 2.6.1

akka-sample-cluster-client-grpc-java/pom.xml, akka-sample-cluster-java/build.sbt, akka-sample-cluster-java/pom.xml, akka-sample-cluster-scala/build.sbt, akka-sample-fsm-java/build.sbt, akka-sample-fsm-java/pom.xml, akka-sample-fsm-scala/build.sbt, akka-sample-persistence-dc-java/build.sbt, akka-sample-persistence-dc-scala/build.sbt, akka-sample-persistence-scala/build.sbt, akka-sample-sharding-java/build.sbt
=> organization com.lightbend.akka.samples

docs-gen/akka-sample-camel-java/build.sbt, docs-gen/akka-sample-camel-scala/build.sbt, docs-gen/akka-sample-multi-node-scala/build.sbt, docs-gen/akka-sample-remote-java/build.sbt, docs-gen/akka-sample-remote-scala/build.sbt, docs-gen/akka-sample-supervision-java/build.sbt
corresponding samples have been removed
I'll check if something has to be removed in techhub
=> remove some obsolete docs-gen

akka-sample-cqrs-java/README.md, akka-sample-cqrs-java/build.sbt, akka-sample-cqrs-java/pom.xml, akka-sample-cqrs-java/src/main/java/sample/cqrs/Main.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCartRoutes.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCartServer.java, akka-sample-cqrs-java/src/main/resources/application.conf
Corresponding for Scala was https://github.com/akka/akka-samples/pull/156
=> add http api to akka-sample-cqrs-java

akka-sample-cluster-scala/src/main/scala/sample/cluster/transformation/App.scala
Fixes a bug in a sample that ignores a parameter, so that the tutorial works again.
=> cluster transformation: correctly use role param

akka-sample-cqrs-java/src/main/java/sample/cqrs/EventProcessorStream.java, akka-sample-cqrs-scala/src/main/scala/sample/cqrs/EventProcessor.scala
* instead of the fixed NoOffset that will result in longer and longer
scanning over time
=> start offset one week back in cqrs sample

akka-sample-distributed-workers-scala/README.md
Fix the Balancing Workload Across Nodes with Akka 2 blog post date. The real one can be found in the [archives](https://letitcrash.com/archive).
=> Fix Balancing Workload Across Nodes with Akka 2 blog post date

akka-sample-cluster-client-grpc-java/pom.xml, akka-sample-cluster-java/pom.xml, akka-sample-cqrs-java/pom.xml, akka-sample-fsm-java/.mvn/extensions.xml, akka-sample-fsm-java/.mvn/jgitver.config.xml, akka-sample-fsm-java/README.md, akka-sample-fsm-java/pom.xml, akka-sample-persistence-dc-java/pom.xml, akka-sample-persistence-java/.mvn/extensions.xml, akka-sample-persistence-java/.mvn/jgitver.config.xml, akka-sample-sharding-java/killrweather-fog/pom.xml, akka-sample-sharding-java/killrweather/pom.xml
=> Maven running on Java 11 fixes

akka-sample-distributed-workers-scala/src/main/resources/application.conf, akka-sample-distributed-workers-scala/src/main/scala/worker/WorkManager.scala
=> Some small fixes to the distributed workers sample

akka-sample-fsm-java/src/main/java/sample/DiningHakkers.java, akka-sample-fsm-java/src/main/java/sample/Hakker.java, akka-sample-fsm-scala/src/main/scala/sample/DiningHakkers.scala
Incorrect message handling.
Took the oportunity to align with style guide and align naming between samples for easier comparison.
References #198
=> Fix Java dining hacker sample not working

akka-sample-cluster-java/src/main/resources/logback.xml, akka-sample-cluster-scala/src/main/resources/logback.xml, akka-sample-cqrs-java/src/main/resources/logback.xml, akka-sample-cqrs-java/src/test/resources/logback-test.xml, akka-sample-cqrs-scala/src/main/resources/logback.xml, akka-sample-cqrs-scala/src/test/resources/logback-test.xml, akka-sample-distributed-data-java/src/main/resources/logback.xml, akka-sample-distributed-data-java/src/test/resources/logback-test.xml, akka-sample-distributed-data-scala/src/main/resources/logback.xml, akka-sample-distributed-data-scala/src/test/resources/logback-test.xml, akka-sample-fsm-java/src/main/resources/logback.xml, akka-sample-fsm-scala/src/main/resources/logback.xml, akka-sample-persistence-dc-java/src/main/resources/logback.xml, akka-sample-persistence-dc-scala/src/main/resources/logback.xml, akka-sample-persistence-java/src/main/resources/logback.xml, akka-sample-persistence-java/src/test/resources/logback-test.xml, akka-sample-persistence-scala/src/main/resources/logback.xml, akka-sample-persistence-scala/src/test/resources/logback-test.xml, akka-sample-sharding-scala/killrweather-fog/src/main/resources/logback.xml, akka-sample-sharding-scala/killrweather/src/main/resources/logback.xml
Same change as in https://github.com/akka/akka/pull/28834
=> change %mdc pattern, same as in Akka docs

akka-sample-persistence-scala/src/main/scala/sample/persistence/ShoppingCart.scala
java sample is ok
cqrs samples are ok
=> missing CborSerializable in persistence sample

akka-sample-cluster-scala/src/main/scala/sample/cluster/simple/App.scala, akka-sample-cluster-scala/src/main/scala/sample/cluster/stats/App.scala, akka-sample-cluster-scala/src/main/scala/sample/cluster/stats/AppOneMaster.scala, akka-sample-cluster-scala/src/main/scala/sample/cluster/stats/StatsWorker.scala, akka-sample-cluster-scala/src/main/scala/sample/cluster/transformation/App.scala
=>  Consistent hashing router in cluster sample

akka-sample-cluster-java/README.md, akka-sample-cluster-java/src/main/java/sample/cluster/stats/App.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/AppOneMaster.java, akka-sample-cluster-java/src/main/java/sample/cluster/stats/StatsWorker.java
=> Use consistent hashing in Java cluster sample

akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCart.java, akka-sample-cqrs-java/src/main/java/sample/cqrs/ShoppingCartRoutes.java, akka-sample-cqrs-java/src/test/java/sample/cqrs/IntegrationTest.java, akka-sample-cqrs-java/src/test/java/sample/cqrs/ProjectionTest.java, akka-sample-cqrs-java/src/test/java/sample/cqrs/ShoppingCartTest.java, akka-sample-cqrs-scala/src/main/scala/sample/cqrs/ShoppingCart.scala, akka-sample-cqrs-scala/src/main/scala/sample/cqrs/ShoppingCartRoutes.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/IntegrationSpec.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/ProjectionSpec.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/ShoppingCartSpec.scala, akka-sample-persistence-java/src/main/java/sample/persistence/ShoppingCart.java, akka-sample-persistence-java/src/test/java/sample/persistence/ShoppingCartTest.java, akka-sample-persistence-scala/src/main/scala/sample/persistence/ShoppingCart.scala, akka-sample-persistence-scala/src/test/scala/sample/persistence/ShoppingCartSpec.scala
We upgraded to 2.6.8 but never added usage of the new StatusReply
=> Use status reply in a few samples

akka-sample-sharding-java/killrweather/src/main/java/sample/killrweather/WeatherStation.java, akka-sample-sharding-scala/killrweather-fog/src/main/scala/sample/killrweather/fog/WeatherStation.scala, akka-sample-sharding-scala/killrweather/src/main/scala/sample/killrweather/WeatherStation.scala
- Fix typo
- Remove unused import
=> Cleanup akka-sample-sharding

akka-sample-cqrs-java/README.md, akka-sample-cqrs-java/pom.xml, akka-sample-cqrs-java/src/test/java/sample/cqrs/ProjectionTest.java, akka-sample-cqrs-scala/README.md, akka-sample-cqrs-scala/build.sbt, akka-sample-cqrs-scala/src/main/scala/sample/cqrs/ShoppingCartServer.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/IntegrationSpec.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/ProjectionSpec.scala, akka-sample-cqrs-scala/src/test/scala/sample/cqrs/ShoppingCartSpec.scala
And also fixes some minor code warnings.
=> Update CQRS samples to use Akka Projection 1.0.0

.travis.yml
Changes .travis.yml to only build main branches. That's what we do in other repos as well. 
If I send a PR and my branch is not from a fork, but on this repo, we will trigger to builds. One for the branch and one for the PR. We only need the PR one.
=> Only build main branches

.travis.yml
=> Replace jabba with apt install of JVM (Akka 2.6)

akka-sample-sharding-scala/README.md
=> update POST url in README

akka-sample-cluster-scala/src/main/scala/sample/cluster/stats/App.scala, akka-sample-cluster-scala/src/main/scala/sample/cluster/transformation/Frontend.scala
- Fixed 2 intellij warnings.
- Fixed reversed parameters
=> Small fixes to samples code
